@startuml Architect
!define RECTANGLE rectangle

actor "ユーザー" as User
rectangle "LINE Messaging API" as LineMessagingAPI
package Back4App {
    rectangle "Webフック先\nASP.NET Core API" as WebHookAPI
}
rectangle "ホットペッパーAPI" as HotPepperAPI
rectangle "YahooLocalAPI" as YahooLocalAPI
package Supabase {
    rectangle "PostgreSQL" as PostgreSQL
}


User --> LineMessagingAPI : 位置情報送信
LineMessagingAPI --> WebHookAPI : Webフック送信
WebHookAPI --> HotPepperAPI : 情報取得
HotPepperAPI --> WebHookAPI : 取得データ返却
WebHookAPI --> YahooLocalAPI : 情報取得
YahooLocalAPI --> WebHookAPI : 取得データ返却
WebHookAPI --> PostgreSQL : データ保存
PostgreSQL --> WebHookAPI : データ取得
WebHookAPI --> LineMessagingAPI : 加工した情報返却
LineMessagingAPI --> User : レスポンス

@enduml
