version: "3.8"
services:
  backend:
    container_name: backend
    build:
      context: ./API
      dockerfile: Dockerfile
    ports:
      - 5000:80
      - 5001:443
    environment:
      - TZ=Asia/Tokyo
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://localhost:5001;http://localhost:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/WslLocalHost.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=WslLocalHost
    network_mode: "host"
    volumes:
      - /${USERPROFILE}/.aspnet/https:/https:ro
