version: "3.8"
services:
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: ./API/Dockerfile
    ports:
      - 5000:5000
      - 5001:5001
    environment:
      - TZ=Asia/Tokyo
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000;https://+:5001
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/WslLocalHost.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=WslLocalHost
    network_mode: "host"
    volumes:
      - /${USERPROFILE}/.aspnet/https:/https:ro
