services:
  server:
    network_mode: bridge
    command: ["sleep", "infinity"]
    volumes:
      - .:/workspaces/LineWebHookAPI
    depends_on:
      - postgres

  postgres:
    ports:
      - 5432:5432
