<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Features.Yahoo</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" Version="8.1.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../Tables/Tables.csproj" />
    <ProjectReference Include="../../Shared/Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="LineDevSdk">
      <HintPath>../../Host/lib/LineDevSdk.dll</HintPath>
    </Reference>
    <Reference Include="YahooDeveloperApiClient">
      <HintPath>../../Host/lib/YahooDeveloperApiClient.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
