<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Application</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="LineDevSdk">
      <HintPath>../Host/lib/LineDevSdk.dll</HintPath>
    </Reference>
    <Reference Include="YahooDeveloperApiClient">
      <HintPath>../Host/lib/YahooDeveloperApiClient.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
