# SDKイメージ
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

# csproj のみをコピーしてリストア
COPY ["LineWebHookAPI/LineWebHookAPI.csproj", "LineWebHookAPI/"]
RUN dotnet restore "LineWebHookAPI/LineWebHookAPI.csproj"

# 残りのファイルをコピーしてビルド
COPY ["LineWebHookAPI/", "LineWebHookAPI/"]
WORKDIR "/src/LineWebHookAPI"
RUN dotnet build "LineWebHookAPI.csproj" -c publish -o /app/build

# パブリッシュ
FROM build AS publish
RUN dotnet publish "LineWebHookAPI.csproj" -c publish -o /app/publish /p:UseAppHost=false

# 実行環境（開発用）SDK イメージを使用し、マイグレードできるようにする
FROM build AS final
WORKDIR /app
EXPOSE 5000
EXPOSE 5001
COPY --from=publish /app/publish /app/bin
COPY LineWebHookAPI/ ./
RUN sed -i 's/DEFAULT@SECLEVEL=2/DEFAULT@SECLEVEL=1/g' /etc/ssl/openssl.cnf && \
    sed -i 's/MinProtocol = TLSv1.2/MinProtocol = TLSv1/g' /etc/ssl/openssl.cnf

# マイグレードコマンドをインストール
RUN dotnet tool install --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"

ENTRYPOINT ["dotnet", "/app/bin/LineWebHookAPI.dll"]