name: Build and deploy ASP.Net Core app to Azure Web App - line-web-hook-api

on:
  push:
    branches: [ develop ]
    paths:
      - 'API/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Restore & Build
        run: |
          dotnet restore ./API/LineWebHookAPI/LineWebHookAPI.csproj
          dotnet build   ./API/LineWebHookAPI/LineWebHookAPI.csproj -c Release --no-restore

      - name: Publish
        run: dotnet publish ./API/LineWebHookAPI/LineWebHookAPI.csproj -c Release -o ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: drop
          path: ./publish/**   # ← publish の“中身”をアップロード

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: drop
          path: ./publish      # ← ここに中身を展開する

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_66E085E0FB724F6B8D456EC67F2148F7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_93108C5E37134A96B342478DAA227AC5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AB1DAF1410C34B939B79B31E4779DAF7 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: line-web-hook-api
          slot-name: Production
          package: ./publish    # ← “publish フォルダそのもの”を指定
